# Author: @Aldo Martinez Alarcon
# Project: DSO-FRONT
name: "$(VersionCodeSWA).$(Rev:r)" # (Not change it)

trigger: "none"
pr: "none"

####################
# Resources Repository
# ibkteam/dso-template
# branch: master (Not change it)
####################
resources:
  repositories:
    - repository: "ibkAzTemplates"
      type: "bitbucket"
      endpoint: "bitbucket-generic-user"
      name: "ibkteam/dso-frontend-template"
      ref: "master"

  pipelines:
    - pipeline: "pipelineoriginuat" # Name of the pipeline resource #  (Not change it)
      source: '\PREV\Deployment\dso-angular-swa-sample-web\dso-angular-swa-sample-web_cd-uat' # Name of the triggering pipeline
      project: "dopjeu2c011dsoapv01"
      trigger:
        branches:
          include:
            - "refs/heads/master"
            - "refs/heads/main"
            - "refs/heads/hotfix/*"

####################
# Call the template of your preference
# check the template out :
# https://bitbucket.org/ibkteam/dso-frontend-template/src/master/
####################
extends:
  template: "src/templates/node-swa/cd-prd.yml@ibkAzTemplates"
  parameters:
    projectName: "DSO"
    componentName: "dso-angular-swa-sample-web"
    workingDir: "app"
    buildOutputPath: "dist"
