# Author: @Aldo Martinez
# Project: DSO-FRONT
name: "1.0.$(Rev:r)" # (Do not change it)

trigger: "none"
pr: "none"

####################
# Resources Repository
# ibkteam/dso-frontend-template
# branch: master (Do not change it)
####################
resources:
  repositories:
    - repository: "ibkAzTemplates"
      type: "bitbucket"
      endpoint: "bitbucket-generic-user"
      name: "ibkteam/dso-frontend-template"
      ref: "master"

  pipelines:
    - pipeline: "pipelineorigindev"
      source: "eureca-frontend_cicd-dev"
      project: "dopjeu2eurcpv01"
      trigger:
        branches:
          include:
            - "refs/heads/master"
            - "refs/heads/main"
            - "refs/heads/hotfix/*"

####################
# Call the template of your preference
# check the template out :
# https://bitbucket.org/ibkteam/dso-frontend-template/src/master/
####################
extends:
  template: "src/templates/node-appservice/cd-uat.yml@ibkAzTemplates"
  parameters:
    projectName: "CSE"
    componentName: "cse-eureca-frontend"
    buildOutputPath: "dist"
    azAppServiceSubscription: "RG_EU2_C003_EURC_UAT_01"
    azAppServiceAppType: "webAppLinux"
    azAppServiceAppName: "wappeu2c003eurcuat01"
    azAppServiceRuntimeStack: "NODE|18-lts"
