apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eureca-frontend
  title: EURECA FRONTEND
  description: |
    Proyecto de frontend de cobro simple
  annotations:
    backstage.io/techdocs-ref: dir:./
    github.com/project-slug: ibkpe-org/eureca-frontend
    sonarqube.org/project-key: cse-pe.interbank:cse-eureca-frontend
  tags:
  - entorno:cloud
  - framework-version:20
  - framework:angular
  - language-version:5-8
  - language:typeScritp
spec:
  type: frontend
  lifecycle: production
  owner: group:default/cse-cobro-simple-eureca
  system: cse
  dependsOn:
    - component:default/eureca-backend
