trigger:
  branches:
    include:
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: 'Build'
        steps:
          - script: |
              echo "Building the application!"
              # Your build commands go here
            displayName: 'Build the application'
          - script: |
              echo $(build.sourceBranch)
              # Your build commands go here
            displayName: 'show branch'
          - script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
            displayName: Set the tag name as an environment variable
          - script: |
              echo $(VERSION_TAG)
              # Your build commands go here
            displayName: 'show variable'
