trigger:
  branches:
    include:
      - refs/tags/*

pr: none

parameters:
  - name: destiny
    displayName: Deploy to
    type: string
    default: uat
    values:
      - dev
      - uat
  - name: runSonarTask
    displayName: SonarCloud
    default: false
    type: boolean
  - name: deployment
    displayName: Deployment
    default: true
    type: boolean

variables:
  vmImageName: 'ubuntu-20.04'

  ${{ if or(contains(variables['Build.SourceBranchName'], 'dev'),eq(parameters.destiny,'dev')) }}:
    mode: 'dev'
    appServiceConnection: 'gr2c003eurcdev01'
    groupName: 'RG_EU2_C003_EURC_DEV_01'
    appServiceName: 'wappeu2c003eurcdev01'

  ${{ elseif or(contains(variables['Build.SourceBranchName'], 'uat'),eq(parameters.destiny,'uat')) }}:
    mode: 'uat'
    appServiceConnection: 'RG_EU2_C003_EURC_UAT_01'
    groupName: 'rg_eu2_c003_eurc_uat_01'
    appServiceName: 'wappeu2c003eurcuat01'

stages:
  - stage: Build
    displayName: Build and push ${{variables.mode}}
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        variables:
          - group: sonar
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '18.x'

          - task: Npm@1
            displayName: 'Install angular'
            inputs:
              command: custom
              verbose: false
              customCommand: 'install -g @angular/cli@17'

          - task: Npm@1
            displayName: 'Install npm'
            inputs:
              workingDir: EurekaAngularProy
              verbose: false

          - ${{ if eq(parameters.runSonarTask, true) }}:
            - task: Npm@1
              displayName: 'Run test '
              env:
                NODE_OPTIONS: --max_old_space_size=16384
              inputs:
                command: custom
                workingDir: EurekaAngularProy
                verbose: false
                customCommand: 'run test --coverage'

            - task: SonarCloudPrepare@1
              inputs:
                azureSubscription: 'SCSonarCloudCS'
                SonarCloud: 'SCSonarCloudCS'
                organization: 'interbank'
                scannerMode: 'CLI'
                configMode: 'manual'
                cliProjectKey: 'bie-pe.interbank.bie.cs-frontend:bie-cs-frontend'
                cliProjectName: 'bie-pe.interbank.bie.cs-frontend:bie-cs-frontend'
                cliSources: '.'
                extraProperties: |
                  sonar.sourceEncoding=UTF-8
                  sonar.sources=$(System.DefaultWorkingDirectory)/EurekaAngularProy/src
                  sonar.exclusions = */node_modules/, */src/assets/*, */src/environments/*, */src/jest.config.ts, */src/main.ts, */src/assets/scripts/*
                  sonar.tests=$(System.DefaultWorkingDirectory)/EurekaAngularProy/src
                  sonar.test.inclusions=**/*.spec.ts
                  sonar.javascript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/EurekaAngularProy/coverage/lcov.info
                  sonar.c.file.suffixes=-
                  sonar.cpp.file.suffixes=-
                  sonar.objc.file.suffixes=-
              displayName: 'Prepare analysis on SonarCloud'

            - task: SonarCloudAnalyze@1
              displayName: 'Run Code Analysis'

            - task: SonarCloudPublish@1
              inputs:
                pollingTimeoutSec: '300'
              displayName: 'Publish Quality Gate Result'

            - powershell: |
                $token = [System.Text.Encoding]::UTF8.GetBytes($env:SonarToken + ":")
                $base64 = [System.Convert]::ToBase64String($token)

                $basicAuth = [string]::Format("Basic {0}", $base64)
                $headers = @{ Authorization = $basicAuth }

                $result = Invoke-RestMethod -Method Get -Uri https://sonarcloud.io/api/qualitygates/project_status?projectKey=bie-pe.interbank.bie.cs-frontend:bie-cs-frontend -Headers $headers
                $result | ConvertTo-Json | Write-Host

                if ($result.projectStatus.status -eq "OK") {
                  Write-Host "Quality Gate Succeeded"
                }else{
                  throw "Quality gate failed"
                }
              displayName: 'Check Sonar Quality Gate'
              env:
                SonarToken: $(sonarcloud.token)

          - task: Npm@1
            displayName: 'Run build '
            inputs:
              command: custom
              workingDir: EurekaAngularProy
              verbose: false
              customCommand: 'run build -- --configuration ${{variables.mode}}'

          - script: |
              echo Creating Directory
              mkdir -p Deploy/ClientApp/dist
              echo Move Directory Deploy
              cp -a dist/EurekaAngularProy/. Deploy/ClientApp/dist/
              ls Deploy/ClientApp/dist/
            workingDirectory: EurekaAngularProy
            displayName: 'Create directory'

          - upload: EurekaAngularProy/dist/EurekaAngularProy
            displayName: 'Publish dist'
            artifact: web-cobrosimple

          - task: ArchiveFiles@2
            displayName: 'Archive File'
            inputs:
              rootFolderOrFile: EurekaAngularProy/Deploy
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'

          - ${{ if eq(parameters.deployment, true) }}:
              - task: AzureCLI@2
                displayName: 'Webapp deployment'
                inputs:
                  azureSubscription: $(appServiceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: 'az webapp deployment source config-zip -g $(groupName) -n $(appServiceName) --src $(Build.ArtifactStagingDirectory)/ClientApp.zip'
