trigger: none
pr: none

parameters:
  - name: 'cdToDev'
    displayName: 'Enable cd To Dev'
    type: boolean
    default: true
  - name: 'cdToUat'
    displayName: 'Enable cd To Uat'
    type: boolean
    default: true
  - name: 'cdToPrd'
    displayName: 'Enable cd To Prd'
    type: boolean
    default: false

variables:
  - name: appServiceConnectionDev
    value: 'gr2c003eurcdev01'
  - name: groupNameDev
    value: 'RG_EU2_C003_EURC_DEV_01'
  - name: appServiceNameDev
    value: 'wappeu2c003eurcdev01'
  - name: appServiceConnectionUat
    value: 'RG_EU2_C003_EURC_UAT_01'
  - name: groupNameUat
    value: 'rg_eu2_c003_eurc_uat_01'
  - name: appServiceNameUat
    value: 'wappeu2c003eurcuat01'
  - name: appServiceConnectionPrd
    value: 'RG_EU2_C003_EURC_UAT_01'
  - name: groupNamePrd
    value: 'rg_eu2_c003_eurc_uat_01'
  - name: appServiceNamePrd
    value: 'wappeu2c003eurcuat01'
  - name: vmImageName
    value: 'ubuntu-20.04'

stages:
  - stage: Build
    condition: |
      or(and(in(variables['Build.Reason'],'Manual','IndividualCI') ,
            in(variables['Build.SourceBranch'],'refs/heads/master')) ,
        and(in(variables['Build.Reason'],'Manual') ,
            or(startsWith(variables['Build.SourceBranch'],'refs/heads/hotfix/'),
                startsWith(variables['Build.SourceBranch'],'refs/heads/release/')))
        )
    displayName: 'Build & Push'
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 14.x'
            inputs:
              versionSpec: 14.x

          - task: Npm@1
            displayName: 'Install angular'
            inputs:
              command: custom
              verbose: false
              customCommand: 'install -g @angular/cli@8'

          - task: Npm@1
            displayName: 'Install npm'
            inputs:
              workingDir: EurekaAngularProy
              verbose: false

          - task: Npm@1
            condition: ${{ eq(parameters.cdToDev , true) }}
            displayName: 'Run build Dev'
            inputs:
              command: custom
              workingDir: EurekaAngularProy
              verbose: false
              customCommand: 'run build -- --configuration dev'

          - script: |
              echo Creating Directory
              mkdir -p Deploy/ClientApp/dist
              echo Move Directory Deploy
              cp -a dist/EurekaAngularProy/. Deploy/ClientApp/dist/
              ls Deploy/ClientApp/dist/
            workingDirectory: EurekaAngularProy
            displayName: 'Create directory Dev'
            condition: ${{ eq(parameters.cdToDev , true) }}

          - task: ArchiveFiles@2
            condition: ${{ eq(parameters.cdToDev , true) }}
            displayName: 'Archive File Dev'
            inputs:
              rootFolderOrFile: EurekaAngularProy/Deploy
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'

          - task: PublishBuildArtifacts@1
            condition: ${{ eq(parameters.cdToDev , true) }}
            displayName: 'Publish Artifact Dev'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'
              ArtifactName: 'cobro-simple-dev'

          - task: Npm@1
            condition: ${{ eq(parameters.cdToUat , true) }}
            displayName: 'Run build Uat'
            inputs:
              command: custom
              workingDir: EurekaAngularProy
              verbose: false
              customCommand: 'run build -- --configuration uat'

          - script: |
              echo Creating Directory
              mkdir -p Deploy/ClientApp/dist
              echo Move Directory Deploy
              cp -a dist/EurekaAngularProy/. Deploy/ClientApp/dist/
              ls Deploy/ClientApp/dist/
            workingDirectory: EurekaAngularProy
            displayName: 'Create directory Uat'
            condition: ${{ eq(parameters.cdToUat , true) }}

          - task: ArchiveFiles@2
            condition: ${{ eq(parameters.cdToUat , true) }}
            displayName: 'Archive File Uat'
            inputs:
              rootFolderOrFile: EurekaAngularProy/Deploy
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'

          - task: PublishBuildArtifacts@1
            condition: ${{ eq(parameters.cdToUat , true) }}
            displayName: 'Publish Artifact Uat'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'
              ArtifactName: 'cobro-simple-uat'

          - task: Npm@1
            condition: ${{ eq(parameters.cdToPrd , true) }}
            displayName: 'Run build Prd'
            inputs:
              command: custom
              workingDir: EurekaAngularProy
              verbose: false
              customCommand: 'run build -- --configuration uat'

          - script: |
              echo Creating Directory
              mkdir -p Deploy/ClientApp/dist
              echo Move Directory Deploy
              cp -a dist/EurekaAngularProy/. Deploy/ClientApp/dist/
              ls Deploy/ClientApp/dist/
            workingDirectory: EurekaAngularProy
            displayName: 'Create directory Prd'
            condition: ${{ eq(parameters.cdToPrd , true) }}

          - task: ArchiveFiles@2
            condition: ${{ eq(parameters.cdToPrd , true) }}
            displayName: 'Archive File Prd'
            inputs:
              rootFolderOrFile: EurekaAngularProy/Deploy
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'

          - task: PublishBuildArtifacts@1
            condition: ${{ eq(parameters.cdToPrd , true) }}
            displayName: 'Publish Artifact Prd'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'
              ArtifactName: 'cobro-simple-prd'

         
  - stage: DevDeploy
    condition: |
      or(and(in(variables['Build.Reason'],'Manual','IndividualCI') ,
            in(variables['Build.SourceBranch'],'refs/heads/master'),
            ${{ parameters.cdToDev }} ),
        and(in(variables['Build.Reason'],'Manual'),
            or(startsWith(variables['Build.SourceBranch'],'refs/heads/hotfix/'),
                startsWith(variables['Build.SourceBranch'],'refs/heads/release/')),
            ${{ parameters.cdToDev }})
        )
    displayName: Deploy to DEV
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy to DEV
        pool:
          vmImage: $(vmImageName)
        environment: 'webappdev'  
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: 'Download Build Artifacts Dev'
                  inputs:
                    artifactName: 'cobro-simple-dev'
                    extractTars: false
                - task: AzureCLI@2
                  displayName: 'Azure CLI Dev'
                  inputs:
                    azureSubscription: $(appServiceConnectionDev)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: 'az webapp deployment source config-zip -g $(groupNameDev) -n $(appServiceNameDev) --src $(System.ArtifactsDirectory)/cobro-simple-dev/ClientApp.zip'
  - stage: UatDeploy
    displayName: Deploy to UAT
    dependsOn: ['Build','DevDeploy']
    condition: |
      or(and(in(variables['Build.Reason'],'Manual','IndividualCI') ,
            in(variables['Build.SourceBranch'],'refs/heads/master'),
            ${{ parameters.cdToUat }} ),
        and(in(variables['Build.Reason'],'Manual'),
            or(startsWith(variables['Build.SourceBranch'],'refs/heads/hotfix/'),
                startsWith(variables['Build.SourceBranch'],'refs/heads/release/')),
            ${{ parameters.cdToUat }})
        )
    jobs:
      - deployment: Deploy
        displayName: Deploy to UAT
        pool:
          vmImage: $(vmImageName)
        environment: 'webappuat'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: 'Download Build Artifacts Uat'
                  inputs:
                    artifactName: 'cobro-simple-uat'
                    extractTars: false
                - task: AzureCLI@2
                  displayName: 'Azure CLI Uat'
                  inputs:
                    azureSubscription: $(appServiceConnectionUat)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: 'az webapp deployment source config-zip -g $(groupNameUat) -n $(appServiceNameUat) --src $(System.ArtifactsDirectory)/cobro-simple-uat/ClientApp.zip'
              
  - stage: PrdDeploy
    displayName: Deploy to PRD
    dependsOn: ['Build','UatDeploy']
    condition: |
      or(and(in(variables['Build.Reason'],'Manual','IndividualCI') ,
            in(variables['Build.SourceBranch'],'refs/heads/master'),
            ${{ parameters.cdToPrd }} ),
        and(in(variables['Build.Reason'],'Manual'),
            or(startsWith(variables['Build.SourceBranch'],'refs/heads/hotfix/'),
                startsWith(variables['Build.SourceBranch'],'refs/heads/release/')),
            ${{ parameters.cdToPrd }})
        )
    jobs:
      - deployment: Deploy
        displayName: Deploy to PRD
        pool:
          vmImage: $(vmImageName)
        environment: 'webappprd'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: 'Download Build Artifacts Prd'
                  inputs:
                    artifactName: 'cobro-simple-prd'
                    extractTars: false
                - task: AzureCLI@2
                  displayName: 'Azure CLI Prd'
                  inputs:
                    azureSubscription: $(appServiceConnectionPrd)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: 'az webapp deployment source config-zip -g $(groupNamePrd) -n $(appServiceNamePrd) --src $(System.ArtifactsDirectory)/cobro-simple-prd/ClientApp.zip'
              
