trigger: none
pr: none

variables:
  appServiceConnection: 'gr2c003eurcdev01'
  groupName: 'RG_EU2_C003_EURC_DEV_01'
  appServiceName: 'wappeu2c003eurcdev01'
  vmImageName: 'ubuntu-20.04'

stages:
- stage: Build
  displayName: Build and push dev
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '14.x'

    - task: Npm@1
      displayName: 'Install angular'
      inputs:
        command: custom
        verbose: false
        customCommand: 'install -g @angular/cli@8'

    - task: Npm@1
      displayName: 'Install npm'
      inputs:
        workingDir: EurekaAngularProy
        verbose: false

    - task: Npm@1
      displayName: 'Run build '
      inputs:
        command: custom
        workingDir: EurekaAngularProy
        verbose: false
        customCommand: 'run build -- --configuration dev'

    - script: |
        echo Creating Directory
        mkdir -p Deploy/ClientApp/dist
        echo Move Directory Deploy
        cp -a dist/EurekaAngularProy/. Deploy/ClientApp/dist/
        ls Deploy/ClientApp/dist/
      workingDirectory: EurekaAngularProy
      displayName: 'Create directory'

    - upload: EurekaAngularProy/dist/EurekaAngularProy
      displayName: 'Publish dist'
      artifact: web-cobrosimple

    - task: ArchiveFiles@2
      displayName: 'Archive File'
      inputs:
        rootFolderOrFile: EurekaAngularProy/Deploy
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/ClientApp.zip'

    - task: AzureCLI@2
      displayName: 'Webapp deployment'
      inputs:
        azureSubscription: $(appServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: 'az webapp deployment source config-zip -g $(groupName) -n $(appServiceName) --src $(Build.ArtifactStagingDirectory)/ClientApp.zip'
