module.exports = {
  content: ['./src/app/**/*.{html,ts}'],
  prefix: 'tw-',
  theme: {
    colors: {
      black: '#000000',
      white: '#ffffff',
      transparent: 'transparent',
      current: 'currentColor',
      error: 'var(--extended-palette-watermelon-1)',
      info: 'var(--extended-palette-lightblue-5)',
      primary: {
        'green-1': 'var(--primary-green-1)',
        'green-2': 'var(--primary-green-2)',
        'green-3': 'var(--primary-green-3)',
        'green-4': 'var(--primary-green-4)',
        'green-5': 'var(--primary-green-5)',
      },
      secondary: {
        'blue-1': 'var(--secondary-blue-1)',
        'blue-2': 'var(--secondary-blue-2)',
        'blue-3': 'var(--secondary-blue-3)',
        'blue-4': 'var(--secondary-blue-4)',
        'blue-5': 'var(--secondary-blue-5)',
      },
      extended: {
        'beige-1': '#f0f0dc',
        'beige-2': '#f3f3e3',
        'beige-3': '#f6f6ea',
        'beige-4': '#f9f9f1',
        'beige-5': '#fcfcf8',
        'ibk-black': '#0f191e',
        'darkblue-1': '#001e5f',
        'darkblue-2': '#334b7f',
        'darkblue-3': '#66789f',
        'darkblue-4': '#99a5bf',
        'darkblue-5': '#ccd2df',
        'grey-1': 'var(--grises-grey-1)',
        'grey-2': '#b7babc',
        'grey-3': '#d9dadb',
        'grey-4': '#eceded',
        'grey-5': '#fbfbfb',
        'lightblue-1': '#64b4e6',
        'lightblue-2': '#83c3eb',
        'lightblue-3': '#a2d2f0',
        'lightblue-4': '#c1e1f5',
        'lightblue-5': '#e0f0fa',
        'orange-1': '#f99100',
        'orange-2': '#fabe64',
        'watermelon-1': '#eb0046',
        'watermelon-2': '#ef336b',
        'watermelon-3': '#f36690',
        'watermelon-4': '#f799b5',
        'watermelon-5': '#fbccda',
        'yellow-1': '#ffcd00',
        'yellow-2': '#ffd733',
        'yellow-3': '#ffe166',
        'yellow-4': '#ffeb99',
        'yellow-5': '#fff5cc',
        'bleached-silk': 'var(--extended-bleached-silk)',
      },
    },
    extend: {
      fontSize: {
        xxs: ['10px', '16px'],
      },
      maxWidth: {
        '8xl': '1320px',
      },
    },
    borderColor: (theme) => ({
      ...theme('colors'),
      'green-1': 'var(--primary-green-1)',
    }),
  },
  plugins: [],
};
