sonar.host.url=https://sonarcloud.io
sonar.organization=interbank
sonar.projectKey=cse-pe.interbank:cse-eureca-frontend
sonar.sourceEncoding=UTF-8
sonar.sources=app/src
sonar.exclusions=**/node_modules/***/src/assets/*, */src/environments/*, */src/jest.config.ts, */src/main.ts, */src/assets/scripts/*, */src/assets/scripts/*, **/*.stories.ts
sonar.tests=app/src
sonar.test.inclusions=**/*.spec.ts
sonar.test.exclusions=**/*.stories.ts
sonar.typescript.lcov.reportPaths=app/testresults/coverage/lcov.info
sonar.testExecutionReportPaths=app/testresults/sonar/sonar-report.xml
